#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan  2 12:32:26 2020

@author: jaco
"""

# http://automatetheboringstuff.com/2e/chapter12/
# http://automatetheboringstuff.com/2e/appendixb/  Appending B

import webbrowser
webbrowser.open("https://inventwithpython.com/")
