#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Dec 19 07:02:24 2019

@author: jaco
"""

# https://www.w3schools.com/python/python_ml_normal_data_distribution.asp

import numpy
import matplotlib.pyplot as plt

# Gaussian distribution of data (Bell curve)
x = numpy.random.normal(5.0,1.0,100000)
plt.hist(x)
plt.show()